---
# tasks file for roles/terraria-server

- name: gather OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "main.yml"
      paths:
        - "vars"
  tags: terraria-server

- name: terraria server required packages (apt)
  apt:
    name: "{{ terraria_server_packages }}"
    state: "present"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
    autoremove: true
    autoclean: true
  tags: terraria-server

- name: create terraria server user
  user:
    name: "tshock"
    comment: "Terraria Server"
    createhome: "no"
    home: "/var/tshock"
    state: "present"
    shell: "/bin/true"
    system: "yes"
  tags: terraria-server

- name: fix permissions on tshock user home directory
  file:
    path: "/var/tshock"
    state: "directory"
    owner: "tshock"
    group: "tshock"
    mode: "2755"
  tags: terraria-server

- name: create tshock server home
  file:
    path: "/usr/local/games/tshock"
    state: "directory"
    owner: "tshock"
    group: "tshock"
    mode: "2755"
  tags: terraria-server

- name: download tshock
  get_url:
    url: "{{ tshock_download }}"
    dest: "/var/tshock"
    sha256sum: "{{ tshock_sha256sum }}"
    mode: "0644"
  register: download
  tags: terraria-server

- debug:
    msg: "download: {{ download }}"
  tags: terraria-server

- name: expand tshock zip file # noqa 503
  unarchive:
    src: "/var/tshock/{{ tshock_filename }}"
    dest: "/usr/local/games/tshock/"
    copy: "no"
    owner: "tshock"
    group: "tshock"
  when:
    - download.changed
  register: unarchive
  notify:
    - "new release"
  tags: terraria-server

- name: tweak motd
  blockinfile:
    block: "{{ lookup('file', 'files/motd.txt') }}"
    dest: /etc/motd
    create: true
  when: tweak_motd
  tags: terraria-server
