---
# handlers file for roles/terraria-server

- name: HANDLER - fix tshock file permissions
  file:
    path: "/usr/local/games/tshock/{{ item.src }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "GeoIP.dat", owner: "tshock", group: "tshock", mode: "0644" }
    - {
        src: "Newtonsoft.Json.dll",
        owner: "tshock",
        group: "tshock",
        mode: "0644",
      }
    - { src: "OTAPI.dll", owner: "tshock", group: "tshock", mode: "0644" }
    - { src: "ServerPlugins", owner: "tshock", group: "tshock", mode: "2755" }
    - {
        src: "TerrariaServer.exe",
        owner: "tshock",
        group: "tshock",
        mode: "0755",
      }
    - { src: "sqlite3.dll", owner: "tshock", group: "tshock", mode: "0644" }
  listen:
    - "new release"
  tags: terraria-server

- name: HANDLER - fix tshock file permissions (sub-directories)
  file:
    path: "/usr/local/games/tshock/ServerPlugins/{{ item.src }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "BCrypt.Net.dll", owner: "tshock", group: "tshock", mode: "0644" }
    - { src: "HttpServer.dll", owner: "tshock", group: "tshock", mode: "0644" }
    - {
        src: "Mono.Data.Sqlite.dll",
        owner: "tshock",
        group: "tshock",
        mode: "0644",
      }
    - { src: "MySql.Data.dll", owner: "tshock", group: "tshock", mode: "0644" }
    - { src: "TShockAPI.dll", owner: "tshock", group: "tshock", mode: "0644" }
  listen:
    - "new release"
  tags: terraria-server
