---
- name: Converge
  hosts: all
  become: true

  vars:
    tshock_filename: "TShock4.4.0_Pre10_Terraria1.4.0.4.zip"
    tshock_download: "https://github.com/Pryaxis/TShock/releases/download/v4.4-pre10/TShock4.4.0_Pre10_Terraria1.4.0.4.zip"
    tshock_sha256sum: "5bf6af4d0541ec4af720b44cf457608771e3d957dd67cfb16ce7bded9800ef93"
    teak_motd: true

  pre_tasks:
    - name: PRE-TASK update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
        autoremove: true
        autoclean: true
      changed_when: false
      when: ansible_os_family == 'Debian'

  roles:
    - role: basictheprogram.terraria_server
