---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ubuntu-20.04
    #    groups: ubuntu-20.04
    #      - server
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
#  inventory:
#    host_vars:
#      tweak_motd: true
#scenario:
#  name: default
verifier:
  #  name: testinfra
  #  lint:
  #    name: flake8
  #  options:
  #    s: true
  name: ansible
  lint:
    name: ansible-lint
